/**
 * lib/menu-data.ts
 * Central authoritative menu data catalog containing all 28 café food items across 6 categories.
 * Each item contains accurate photographic images saved locally in /images/food/<slug>.jpg.
 */

export interface CafeMenuItem {
  id: string;
  category_id: string;
  category_name: string;
  name: string;
  description: string;
  price: number;
  availability: 'available' | 'limited' | 'unavailable';
  spoken_aliases: string[];
  allergens: string[];
  prep_time_minutes: number;
  station: 'Espresso Bar' | 'Slow Bar' | 'Fryer & Snacks' | 'Griddle & Tiffin' | 'Bakery' | 'Main Kitchen';
  badge?: string;
  image: string;
  spokenQuery?: string;
}

export interface CafeMenuCategory {
  id: string;
  name: string;
  display_order: number;
  description: string;
  iconName: string;
}

export const MENU_CATEGORIES: CafeMenuCategory[] = [
  { id: 'cat-1', name: 'Hot Beverages', display_order: 1, description: 'Traditional and artisanal hot brews', iconName: 'Coffee' },
  { id: 'cat-2', name: 'Cold Beverages', display_order: 2, description: 'Chilled coffees, coolers, and traditional lassis', iconName: 'GlassWater' },
  { id: 'cat-3', name: 'Hot Snacks & Savories', display_order: 3, description: 'Crispy snacks, rolls, and street classics', iconName: 'UtensilsCrossed' },
  { id: 'cat-4', name: 'Tiffin & Breakfast', display_order: 4, description: 'South Indian morning staples & sourdough toasts', iconName: 'Flame' },
  { id: 'cat-5', name: 'Bakery & Desserts', display_order: 5, description: 'Fresh French pastries & warm handcrafted desserts', iconName: 'Cake' },
  { id: 'cat-6', name: 'Main Course', display_order: 6, description: 'Comforting bowls and chef signature pastas', iconName: 'ChefHat' },
];

export const ALL_FOOD_ITEMS: CafeMenuItem[] = [
  // ── Hot Beverages ───────────────────────────────────────────────────────────
  {
    id: 'item-1',
    category_id: 'cat-1',
    category_name: 'Hot Beverages',
    name: 'South Indian Filter Coffee',
    description: 'Traditional freshly brewed chicory blend with frothy milk, served dabarah style.',
    price: 40,
    availability: 'available',
    spoken_aliases: ['filter coffee', 'kaapi', 'coffee', 'degree coffee', 'hot coffee', 'filter kaapi', 'south indian coffee'],
    allergens: ['milk'],
    prep_time_minutes: 3,
    station: 'Espresso Bar',
    badge: 'Heritage Brew',
    image: '/images/food/filter-coffee.jpg',
    spokenQuery: '“Oka hot filter coffee dabarah style lo ivvandi.”',
  },
  {
    id: 'item-2',
    category_id: 'cat-1',
    category_name: 'Hot Beverages',
    name: 'Cutting Masala Chai',
    description: 'Ginger, cardamom, and clove infused hot milk tea brewed to kadak perfection.',
    price: 30,
    availability: 'available',
    spoken_aliases: ['masala chai', 'chai', 'tea', 'garam chai', 'adrak chai', 'cutting chai', 'kadak chai'],
    allergens: ['milk'],
    prep_time_minutes: 3,
    station: 'Espresso Bar',
    badge: 'Street Kadak',
    image: '/images/food/masala-chai.jpg',
    spokenQuery: '“Ek cutting kadak masala chai jaldi bana do.”',
  },
  {
    id: 'item-3',
    category_id: 'cat-1',
    category_name: 'Hot Beverages',
    name: 'Classic Espresso',
    description: 'A single shot of rich, concentrated espresso with a velvety golden crema.',
    price: 120,
    availability: 'available',
    spoken_aliases: ['espresso', 'short black', 'single shot'],
    allergens: [],
    prep_time_minutes: 3,
    station: 'Espresso Bar',
    badge: 'Pure Arabica',
    image: '/images/food/espresso.jpg',
    spokenQuery: '“One double shot espresso with golden crema please.”',
  },
  {
    id: 'item-4',
    category_id: 'cat-1',
    category_name: 'Hot Beverages',
    name: 'Cappuccino',
    description: 'Espresso topped with equal parts velvety steamed milk and thick foam.',
    price: 180,
    availability: 'available',
    spoken_aliases: ['cappuccino', 'capp', 'frothy coffee'],
    allergens: ['milk'],
    prep_time_minutes: 5,
    station: 'Espresso Bar',
    badge: 'Signature',
    image: '/images/food/cappuccino.jpg',
    spokenQuery: '“Two oat milk cappuccinos with extra foam.”',
  },
  {
    id: 'item-5',
    category_id: 'cat-1',
    category_name: 'Hot Beverages',
    name: 'Masala Chai Latte',
    description: 'Spiced Indian tea reduction frothed with micro-textured steamed milk.',
    price: 150,
    availability: 'available',
    spoken_aliases: ['chai latte', 'spiced tea latte'],
    allergens: ['milk'],
    prep_time_minutes: 5,
    station: 'Espresso Bar',
    badge: 'Fusion Special',
    image: '/images/food/chai-latte.jpg',
    spokenQuery: '“Can I get a hot Masala Chai Latte parcel?”',
  },
  {
    id: 'item-6',
    category_id: 'cat-1',
    category_name: 'Hot Beverages',
    name: 'Hot Chocolate',
    description: 'Creamy Belgian chocolate melted with steamed milk, topped with whipped cream.',
    price: 200,
    availability: 'available',
    spoken_aliases: ['hot choco', 'chocolate drink', 'cocoa'],
    allergens: ['milk'],
    prep_time_minutes: 5,
    station: 'Espresso Bar',
    badge: 'Belgian Cocoa',
    image: '/images/food/hot-chocolate.jpg',
    spokenQuery: '“One rich hot chocolate with extra marshmallow cream.”',
  },

  // ── Cold Beverages ──────────────────────────────────────────────────────────
  {
    id: 'item-7',
    category_id: 'cat-2',
    category_name: 'Cold Beverages',
    name: 'Cold Brew Coffee',
    description: '18-hour cold-steeped single-origin coffee, smooth and low in acidity over ice.',
    price: 220,
    availability: 'available',
    spoken_aliases: ['cold brew', 'iced coffee'],
    allergens: [],
    prep_time_minutes: 2,
    station: 'Slow Bar',
    badge: 'Single Origin',
    image: '/images/food/cold-brew.jpg',
    spokenQuery: '“One slow steeped cold brew, black over clear ice.”',
  },
  {
    id: 'item-8',
    category_id: 'cat-2',
    category_name: 'Cold Beverages',
    name: 'Classic Cold Coffee',
    description: 'Creamy blended chilled milk coffee with vanilla bean and rich espresso froth.',
    price: 70,
    availability: 'available',
    spoken_aliases: ['cold coffee', 'frappe', 'thick cold coffee'],
    allergens: ['milk'],
    prep_time_minutes: 4,
    station: 'Slow Bar',
    badge: 'Crowd Favorite',
    image: '/images/food/cold-coffee.jpg',
    spokenQuery: '“Do classic thick cold coffee parcel cheyyandi.”',
  },
  {
    id: 'item-9',
    category_id: 'cat-2',
    category_name: 'Cold Beverages',
    name: 'Mango Lassi',
    description: 'Fresh Alphonso mango blended with thick yogurt and a hint of green cardamom.',
    price: 160,
    availability: 'available',
    spoken_aliases: ['mango lassi', 'mango drink', 'lassi'],
    allergens: ['milk'],
    prep_time_minutes: 4,
    station: 'Slow Bar',
    badge: 'Alphonso Pure',
    image: '/images/food/mango-lassi.jpg',
    spokenQuery: '“One chilled mango lassi with extra pistachio garnish.”',
  },
  {
    id: 'item-10',
    category_id: 'cat-2',
    category_name: 'Cold Beverages',
    name: 'Watermelon Mint Cooler',
    description: 'Fresh crushed watermelon juice with garden mint and a dash of black salt.',
    price: 140,
    availability: 'available',
    spoken_aliases: ['watermelon cooler', 'mint cooler', 'watermelon juice'],
    allergens: [],
    prep_time_minutes: 4,
    station: 'Slow Bar',
    badge: 'Zero Sugar Added',
    image: '/images/food/watermelon-cooler.jpg',
    spokenQuery: '“Ek watermelon mint cooler refreshing black salt ke sath.”',
  },

  // ── Hot Snacks & Savories ───────────────────────────────────────────────────
  {
    id: 'item-11',
    category_id: 'cat-3',
    category_name: 'Hot Snacks & Savories',
    name: 'Samosa (2 pcs)',
    description: 'Crispy golden flaky pastry stuffed with spiced potatoes and green peas.',
    price: 50,
    availability: 'available',
    spoken_aliases: ['samosa', 'samose', 'samosas', 'singara', 'aloo samosa', 'two samosas', 'do samosa'],
    allergens: ['gluten'],
    prep_time_minutes: 6,
    station: 'Fryer & Snacks',
    badge: 'Fresh Fry',
    image: '/images/food/samosa.jpg',
    spokenQuery: '“Bhaiya, do plate garam samosa aur meethi chutney dena.”',
  },
  {
    id: 'item-12',
    category_id: 'cat-3',
    category_name: 'Hot Snacks & Savories',
    name: 'Masala Vada Pav',
    description: 'Spicy potato fritter in a soft pav bun with garlic chutney and fried chili.',
    price: 80,
    availability: 'available',
    spoken_aliases: ['vada pav', 'vada', 'potato bun', 'mumbai vada pav'],
    allergens: ['gluten'],
    prep_time_minutes: 6,
    station: 'Fryer & Snacks',
    badge: 'Mumbai Classic',
    image: '/images/food/vada-pav.jpg',
    spokenQuery: '“Ek spicy Mumbai vada pav with roasted green chili.”',
  },
  {
    id: 'item-13',
    category_id: 'cat-3',
    category_name: 'Hot Snacks & Savories',
    name: 'Spiced Veg Puff',
    description: 'Golden puff pastry layered with aromatic curried carrots, peas, and potatoes.',
    price: 45,
    availability: 'available',
    spoken_aliases: ['veg puff', 'puff', 'curry puff', 'patties', 'veg patty'],
    allergens: ['gluten'],
    prep_time_minutes: 4,
    station: 'Fryer & Snacks',
    badge: 'Flaky Bake',
    image: '/images/food/veg-puff.jpg',
    spokenQuery: '“Two hot crispy veg puffs parcel kar dijiye.”',
  },
  {
    id: 'item-14',
    category_id: 'cat-3',
    category_name: 'Hot Snacks & Savories',
    name: 'Paneer Roll',
    description: 'Spiced paneer cubes with sautéed onions wrapped in a crisp paratha.',
    price: 80,
    availability: 'available',
    spoken_aliases: ['paneer roll', 'paneer wrap', 'frankie'],
    allergens: ['gluten', 'milk'],
    prep_time_minutes: 8,
    station: 'Fryer & Snacks',
    badge: 'Chef Wrap',
    image: '/images/food/paneer-roll.jpg',
    spokenQuery: '“Oka hot paneer roll parcel chesi ivvandi.”',
  },
  {
    id: 'item-15',
    category_id: 'cat-3',
    category_name: 'Hot Snacks & Savories',
    name: 'Paneer Tikka Wrap',
    description: 'Char-grilled tandoori paneer and bell peppers in whole-wheat wrap with mint chutney.',
    price: 260,
    availability: 'available',
    spoken_aliases: ['paneer wrap', 'tikka wrap', 'cottage cheese wrap'],
    allergens: ['gluten', 'milk'],
    prep_time_minutes: 12,
    station: 'Fryer & Snacks',
    badge: 'Tandoori Roast',
    image: '/images/food/paneer-tikka-wrap.jpg',
    spokenQuery: '“One smoky paneer tikka wrap with mint chutney.”',
  },
  {
    id: 'item-16',
    category_id: 'cat-3',
    category_name: 'Hot Snacks & Savories',
    name: 'Medu Vada (2 pcs)',
    description: 'Crispy fried lentil doughnuts with crunchy exterior, served with coconut chutney.',
    price: 60,
    availability: 'available',
    spoken_aliases: ['vada', 'medu vada', 'wada', 'garelu', 'two vadas'],
    allergens: [],
    prep_time_minutes: 5,
    station: 'Fryer & Snacks',
    badge: 'Crispy Lentil',
    image: '/images/food/medu-vada.jpg',
    spokenQuery: '“Rendu crispy medu vadas with hot sambar and chutney.”',
  },
  {
    id: 'item-17',
    category_id: 'cat-3',
    category_name: 'Hot Snacks & Savories',
    name: 'Cheese Garlic Bread',
    description: 'Toasted ciabatta slices brushed with garlic herb butter and melted mozzarella.',
    price: 130,
    availability: 'available',
    spoken_aliases: ['garlic bread', 'cheese bread', 'cheesy garlic'],
    allergens: ['gluten', 'milk'],
    prep_time_minutes: 8,
    station: 'Fryer & Snacks',
    badge: 'Melted Mozzarella',
    image: '/images/food/cheese-garlic-bread.jpg',
    spokenQuery: '“One cheese garlic bread, extra oregano please.”',
  },
  {
    id: 'item-18',
    category_id: 'cat-3',
    category_name: 'Hot Snacks & Savories',
    name: 'Crispy Corn Chaat',
    description: 'Flash-fried sweet corn tossed with diced red onion, lime, and chaat spices.',
    price: 160,
    availability: 'available',
    spoken_aliases: ['corn chaat', 'crispy corn', 'fried corn'],
    allergens: [],
    prep_time_minutes: 8,
    station: 'Fryer & Snacks',
    badge: 'Tangy Crunch',
    image: '/images/food/corn-chaat.jpg',
    spokenQuery: '“Ek spicy crispy corn chaat thoda extra lemon ke sath.”',
  },

  // ── Tiffin & Breakfast ──────────────────────────────────────────────────────
  {
    id: 'item-19',
    category_id: 'cat-4',
    category_name: 'Tiffin & Breakfast',
    name: 'Irani Bun Maska',
    description: 'Warm soft bakery bun sliced and stuffed with rich sweet cream butter slab.',
    price: 50,
    availability: 'available',
    spoken_aliases: ['bun maska', 'maska bun', 'butter bun'],
    allergens: ['gluten', 'milk'],
    prep_time_minutes: 3,
    station: 'Griddle & Tiffin',
    badge: 'Irani Classic',
    image: '/images/food/bun-maska.jpg',
    spokenQuery: '“Ek Bun Maska aur ek Cutting Chai saath me lagao.”',
  },
  {
    id: 'item-20',
    category_id: 'cat-4',
    category_name: 'Tiffin & Breakfast',
    name: 'Tawa Masala Dosa',
    description: 'Crispy golden fermented rice crepe filled with spiced tempered potato mash.',
    price: 90,
    availability: 'available',
    spoken_aliases: ['dosa', 'masala dosa', 'dosalu', 'masale dosa'],
    allergens: [],
    prep_time_minutes: 8,
    station: 'Griddle & Tiffin',
    badge: 'Crispy Crepe',
    image: '/images/food/masala-dosa.jpg',
    spokenQuery: '“One crispy Tawa Masala Dosa, sambar separate.”',
  },
  {
    id: 'item-21',
    category_id: 'cat-4',
    category_name: 'Tiffin & Breakfast',
    name: 'Avocado Toast',
    description: 'Toasted artisanal sourdough topped with crushed avocado, cherry tomatoes, and feta.',
    price: 280,
    availability: 'available',
    spoken_aliases: ['avocado toast', 'avo toast', 'avocado bread'],
    allergens: ['gluten', 'milk'],
    prep_time_minutes: 8,
    station: 'Griddle & Tiffin',
    badge: 'Artisanal Sourdough',
    image: '/images/food/avocado-toast.jpg',
    spokenQuery: '“One fresh avocado toast on sourdough with feta.”',
  },

  // ── Bakery & Desserts ───────────────────────────────────────────────────────
  {
    id: 'item-22',
    category_id: 'cat-5',
    category_name: 'Bakery & Desserts',
    name: 'Butter Croissant',
    description: 'Flaky, buttery French laminated pastry baked fresh and served golden crisp.',
    price: 90,
    availability: 'available',
    spoken_aliases: ['croissant', 'butter croissant'],
    allergens: ['gluten', 'milk'],
    prep_time_minutes: 4,
    station: 'Bakery',
    badge: 'Pure Butter Layer',
    image: '/images/food/croissant.jpg',
    spokenQuery: '“Ek warm butter croissant pack kar do.”',
  },
  {
    id: 'item-23',
    category_id: 'cat-5',
    category_name: 'Bakery & Desserts',
    name: 'Chocolate Muffin',
    description: 'Double chocolate chip sponge muffin with rich cocoa core and ganache drops.',
    price: 65,
    availability: 'available',
    spoken_aliases: ['muffin', 'chocolate muffin', 'cupcake'],
    allergens: ['gluten', 'milk'],
    prep_time_minutes: 3,
    station: 'Bakery',
    badge: 'Double Choco Chip',
    image: '/images/food/chocolate-muffin.jpg',
    spokenQuery: '“Two chocolate muffins fresh from the bakery display.”',
  },
  {
    id: 'item-24',
    category_id: 'cat-5',
    category_name: 'Bakery & Desserts',
    name: 'Warm Chocolate Brownie',
    description: 'Fudgy dark chocolate walnut brownie served warm with vanilla cream.',
    price: 180,
    availability: 'available',
    spoken_aliases: ['brownie', 'choco brownie', 'chocolate cake'],
    allergens: ['gluten', 'milk'],
    prep_time_minutes: 6,
    station: 'Bakery',
    badge: 'Fudgy Walnut',
    image: '/images/food/chocolate-brownie.jpg',
    spokenQuery: '“One warm chocolate walnut brownie for takeaway.”',
  },
  {
    id: 'item-25',
    category_id: 'cat-5',
    category_name: 'Bakery & Desserts',
    name: 'Gulab Jamun (2 pcs)',
    description: 'Soft melt-in-mouth milk dumplings soaked in saffron rose aromatic syrup.',
    price: 120,
    availability: 'available',
    spoken_aliases: ['gulab jamun', 'jamun', 'sweet dumplings', 'two gulab jamun'],
    allergens: ['milk', 'gluten'],
    prep_time_minutes: 3,
    station: 'Bakery',
    badge: 'Saffron Rose Syrup',
    image: '/images/food/gulab-jamun.jpg',
    spokenQuery: '“Rendu warm gulab jamuns parcel cheyyandi.”',
  },
  {
    id: 'item-26',
    category_id: 'cat-5',
    category_name: 'Bakery & Desserts',
    name: 'Mango Panna Cotta',
    description: 'Silky vanilla set cream infused with cardamom and Alphonso mango glaze.',
    price: 160,
    availability: 'available',
    spoken_aliases: ['panna cotta', 'mango dessert', 'Italian dessert'],
    allergens: ['milk'],
    prep_time_minutes: 3,
    station: 'Bakery',
    badge: 'Alphonso Glaze',
    image: '/images/food/mango-panna-cotta.jpg',
    spokenQuery: '“One mango panna cotta chilled in dessert jar.”',
  },

  // ── Main Course ─────────────────────────────────────────────────────────────
  {
    id: 'item-27',
    category_id: 'cat-6',
    category_name: 'Main Course',
    name: 'Dal Makhani Bowl',
    description: 'Overnight slow-cooked black lentils in rich butter-tomato gravy with jeera rice.',
    price: 250,
    availability: 'available',
    spoken_aliases: ['dal makhani', 'dal bowl', 'lentil bowl', 'black dal'],
    allergens: ['milk'],
    prep_time_minutes: 12,
    station: 'Main Kitchen',
    badge: 'Slow Simmered',
    image: '/images/food/dal-makhani.jpg',
    spokenQuery: '“Ek Dal Makhani rice bowl parcel ready kar do.”',
  },
  {
    id: 'item-28',
    category_id: 'cat-6',
    category_name: 'Main Course',
    name: 'Creamy Mushroom Pasta',
    description: 'Penne tossed with button and cremini mushrooms in garlic Parmesan cream sauce.',
    price: 320,
    availability: 'available',
    spoken_aliases: ['mushroom pasta', 'pasta', 'creamy pasta'],
    allergens: ['gluten', 'milk'],
    prep_time_minutes: 15,
    station: 'Main Kitchen',
    badge: 'Garlic Parmesan',
    image: '/images/food/mushroom-pasta.jpg',
    spokenQuery: '“One creamy mushroom penne pasta with garlic bread.”',
  },
];

export function getMenuItemsByCategory(categoryId: string): CafeMenuItem[] {
  return ALL_FOOD_ITEMS.filter((item) => item.category_id === categoryId);
}

export function getMenuItemsByStation(station: string): CafeMenuItem[] {
  return ALL_FOOD_ITEMS.filter((item) => item.station === station);
}

export function findMenuItemById(id: string): CafeMenuItem | undefined {
  return ALL_FOOD_ITEMS.find((item) => item.id === id);
}

export function findImageByName(name: string): string {
  const norm = name.toLowerCase();
  const match = ALL_FOOD_ITEMS.find((item) =>
    norm.includes(item.name.toLowerCase()) ||
    item.name.toLowerCase().includes(norm) ||
    item.spoken_aliases.some((a) => norm.includes(a.toLowerCase()))
  );
  return match?.image || '/images/food/filter-coffee.jpg';
}
